name: trigger-tf

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run the workflow on'
        required: true
        type: string
        default: 'main' # Or your default branch name

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps: 
    - name: test
      run: |
        terraform -v
        terraform init
